# Generated by Django 4.2.7 on 2025-10-20 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('txt', 'TXT')], max_length=10)),
                ('file_size', models.PositiveIntegerField()),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extraction_error', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('resume_text', models.TextField()),
                ('resume_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('similarity_score', models.FloatField()),
                ('fit_explanation', models.TextField()),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('extracted_experience', models.JSONField(blank=True, default=dict)),
                ('extracted_education', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding_model', models.CharField(default='openai', max_length=100)),
                ('analysis_version', models.CharField(default='1.0', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_time', models.FloatField()),
                ('embedding_time', models.FloatField(blank=True, null=True)),
                ('llm_response_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding_dimensions', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('embedding', 'Generating Embeddings'), ('analyzing', 'Analyzing Fit'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.jobanalysis')),
            ],
            options={
                'verbose_name_plural': 'Analysis histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobanalysis',
            index=models.Index(fields=['job_title'], name='api_jobanal_job_tit_581cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='jobanalysis',
            index=models.Index(fields=['created_at'], name='api_jobanal_created_992acf_idx'),
        ),
        migrations.AddIndex(
            model_name='jobanalysis',
            index=models.Index(fields=['similarity_score'], name='api_jobanal_similar_930245_idx'),
        ),
    ]
